spring:
  datasource:
    url: jdbc:mysql://192.168.1.235:3306/db_test?useSSL=false&setUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: admin
    password: npQsd8a
  redis:
    host: redis.data.ysujc.com
    password: Ym8s9tp
    port: 6379
    timeout: 60000

platform:
  # 超时时间单位（秒），缓存开启时生效
  time-out: 300
  # 是否开启Redis缓存
  redis-cache: true

#用于心跳检测输出的日志
logging:
  level:
    root: INFO

